### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.walrussoup.tailwindformatternext.actions.FormatFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. 

### ISSUE THREAD

**Issue by Van4kk** [WalrusSoup/Tailwind-Formatter#86]
```log
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.walrussoup.tailwindformatternext.actions.FormatFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.myoutdesk.tailwind_formatter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

I'm getting this error when I'm saving the file on `PhpStorm 2024.1.3`. `Build #PS-241.17890.8, built on June 4, 2024`.

**Comment by Manzadey** [comment]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.walrussoup.tailwindformatternext.actions.FormatProjectAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.myoutdesk.tailwind_formatter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
About phpstrom:
```
PhpStorm 2024.2
Build #PS-242.20224.361, built on August 10, 2024
Licensed to Andrey Manzadey
You have a perpetual fallback license for this version.
Subscription is active until September 20, 2025.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.jetbrains.space (242.20224.155)
  com.github.wenzewoo.jetbrains.plugin.jetbrains-markdown-image-support (1.4.1-SNAPSHOT)
  com.myoutdesk.tailwind_formatter (2.0.12)
  DBN (3.4.4425.0)
  com.intellij.ideolog (242.20224.428)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.wakatime.intellij.plugin (15.0.3)
  com.jetbrains.plugins.jslint (202.3)
  com.dmarcotte.handlebars (242.20224.159)
  com.github.inxilpro.intellijalpine (v0.4.2)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
  com.chrisrm.idea.MaterialThemeUI (9.4.1)
  ru.adelf.idea.dotenv (2024.2.1)
  nl.deschepers.laraveltinker (2.7.3)
  de.espend.idea.php.annotation (11.0.3)
  fr.adrienbrault.idea.symfony2plugin (2024.1.276)
  dev.nybroe.collector (1.0.0)
  com.laravel_idea.plugin (8.4.0.242)
  dev.ekvedaras.laravelquery (4.0.4)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
  mobi.hsz.idea.gitignore (4.5.3)
```
