### ISSUE TITLE
com.intellij.diagnostic.PluginException

### ISSUE THREAD

**Issue by timgavin** [WalrusSoup/Tailwind-Formatter#90]
Plugin version 2.0.11

This crash happens every time I access the "Code" menu in the menubar. This seems to be consistent behavior between restarts of PhpStorm. Haven't been able to reproduce any other behavior; even when running the keyboard shortcut the plugin does not crash.

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.walrussoup.tailwindformatternext.actions.FormatFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.myoutdesk.tailwind_formatter]
at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by krekas** [comment]
Can confirm
